jwt:
  access-token-expiration-time: ${ATK_EXP}
  refresh-token-expiration-time: ${RTK_EXP}
  secret: ${JWT_SECRET}

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl1;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

address:
  local: ${LOCAL_ADDRESS}
  domain: ${DOMAIN_ADDRESS}
  front-local: ${FRONT_LOCAL}
  front-s3: ${FRONT_S3}

awsParameterStorePropertySource:
  enabled: true

naver:
  id: ${/config/cloud-parameter-store/naver-id}
  password: ${/config/cloud-parameter-store/naver-password}
