spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${/config/cloud-parameter-store/db-user}
    password: ${/config/cloud-parameter-store/db-password}
    url: ${/config/cloud-parameter-store/db-url}
  jpa:
    hibernate:
      ddl-auto: update # create / update / validate / none
      # 아직 개발중이라 변동사항이 많아서 update로 설정 추후 none or validate로 변경
